apiVersion: v1
kind: Pod
metadata:
  name: bh23
spec:
  containers:
  - name: bh23
    image: docker.io/redhat/ubi8:latest
    tty: true
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME","SYS_ADMIN"]
      privileged: true
    volumeMounts:
      - mountPath: /host/proc
        name: proc-volume
      - mountPath: /docker.sock
        name: var-volume  
  volumes:
        - name: proc-volume
          hostPath:
            path: /proc
        - name: var-volume
          hostPath:
            path: /var/run/docker.sock
                  

