
name: Build Binaries
run-name: Build binaries for x64 and arm
on: [workflow_dispatch]
jobs:
  Build_x64:
    if: true
    runs-on: ubuntu-20.04
    container: 
     image: redhat/ubi8
    steps:
      - uses: actions/checkout@v4
        with:
          repository: DockerExploitationFramework/DockerExploitationFramework
      - run: ls -la
      - run: pwd
      - run: cat /etc/os-release
      - run: yum -y install python3.11-pip gcc gcc-c++ zlib-devel
      - run: pip3 install wheel pyinstaller
      - run: cd lib;ls -la;pwd
      - run: ls -la
      - run: pwd
      - run: pip3 install lib/
      - run: pip3 install -r /shared/requirements.txt
      - run: cd plugins; ./build_all.sh
      - run: tar -czf /tmp/DEF_x86_64.tar.gz .
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
         name: DEF linux (x86_64)
         path: /tmp/DEF_x86_64.tar.gz
         retention-days: 1

  Build_ARM:
    if: true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: DockerExploitationFramework/DockerExploitationFramework    
      - run: docker run --rm --privileged multiarch/qemu-user-static:register
      - run: sudo apt-get update
      - run: sudo apt-get install qemu binfmt-support qemu-user-static
      - run: docker run -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static --platform linux/arm64 redhat/ubi8 arch
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with: 
          image: redhat/ubi8
          options: -v ${{ github.workspace }}:/shared -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static
          run: |
              arch
              uname -a
              ls -la /shared
              ls -la /usr/bin/qemu-aarch64-static
              cat /shared/semicolon_delimited_script
              yum -y install python3.11-pip gcc gcc-c++ zlib-devel
              pip3 install wheel pyinstaller
              pip3 install /shared/lib/
              pip3 install -r /shared/requirements.txt
              cd /shared/plugins; ./build_all.sh
              cd /shared/
              tar -czf /tmp/DEF_arm64.tar.gz .
              cp /tmp/DEF_arm64.tar.gz /shared/
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
         name: DEF linux (arm64)
         path: DEF_arm64.tar.gz
         retention-days: 1
